services:

  frontend:
    image: mohamedmufeed/frontend
    container_name: frontend
    pull_policy: always
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: mohamedmufeed/backend
    container_name: backend
    pull_policy: always
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  peer:
    image: mohamedmufeed/peer
    container_name: peer
    pull_policy: always
    ports:
      - "9000:9000"
    depends_on:
      - backend
    networks:
      - app-network
    command: ["npx", "ts-node", "src/peerServer.ts"]

networks:
  app-network:
    driver: bridge
