version: '3.8'
services:

  frontend:
    container_name: frontend-1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: backend-1
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env.docker
    networks:
      - app-network

  peer:
    container_name: peer-1
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["npx", "ts-node", "src/peerServer.ts"]
    ports:
      - "9000:9000"
    depends_on:
      - backend
    networks:
      - app-network

  # nginx:
  #   container_name: nginx-1
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - frontend
  #     - backend
  #     - peer
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
